# Generated by Django 4.0.5 on 2022-06-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'Catagories'},
        ),
    ]
